INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE, STATUS_DESCRIPTION) VALUES (1, 'PUBLISHED', 'published status');
INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE, STATUS_DESCRIPTION) VALUES (2, 'TESTED', 'tested status');
INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE, STATUS_DESCRIPTION) VALUES (3, 'INACTIVE', 'inactive status');
INSERT INTO SUB_SYSTEM_CATEGORY(ID, CATEGORY_TYPE, CATEGORY_DESCRIPTION) VALUES (1, 'ARZI', 'arzi category');
INSERT INTO SUB_SYSTEM_CATEGORY(ID, CATEGORY_TYPE, CATEGORY_DESCRIPTION) VALUES (2, 'CHANNEL_MANAGER', 'channel manager category');
INSERT INTO CONTEXT_PATH_EUREKA_SERVICE_MAPPING (ID, CONTEXT_PATH, EUREKA_SERVICE_NAME, EUREKA_SERVICE_STATUS_ID, SUB_SYSTEM_CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1, 'accounts', 'account-service', 1, 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
--INSERT INTO CONTEXT_PATH_EUREKA_SERVICE_MAPPING (ID, CONTEXT_PATH, EUREKA_SERVICE_NAME, EUREKA_SERVICE_STATUS_ID, SUB_SYSTEM_CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2, 'customers', 'customer-service', 1, 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );