INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE) VALUES (1, 'PUBLISHED');
INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE) VALUES (2, 'TESTED');
INSERT INTO EUREKA_SERVICE_STATUS(ID, STATUS_TYPE) VALUES (3, 'INACTIVE');
INSERT INTO SUB_SYSTEM_CATEGORY(ID, CATEGORY_TYPE) VALUES (1, 'ARZI');
INSERT INTO SUB_SYSTEM_CATEGORY(ID, CATEGORY_TYPE) VALUES (2, 'CHANNEL_MANAGER');
INSERT INTO CONTEXT_PATH_EUREKA_SERVICE_MAPPING (ID, CONTEXT_PATH, EUREKA_SERVICE_NAME, EUREKA_SERVICE_STATUS_ID, SUB_SYSTEM_CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1, 'accounts', 'account-eurekaServiceName', 1, 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );
INSERT INTO CONTEXT_PATH_EUREKA_SERVICE_MAPPING (ID, CONTEXT_PATH, EUREKA_SERVICE_NAME, EUREKA_SERVICE_STATUS_ID, SUB_SYSTEM_CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2, 'customers', 'customer-eurekaServiceName', 1, 1, CURRENT_TIMESTAMP , CURRENT_TIMESTAMP );